repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: [--fix]
  - repo: local
    hooks:
      - id: l10n
        name: update translations
        entry: ./l10n.sh
        language: system
        pass_filenames: false
        files: ^(virtualbricks/.*\.py|locale/virtualbricks/.*\.po)$
