#!/usr/bin/python
import sys
import time
from  virtualbricks import VBGUI, BrickFactory

#Main.

if len(sys.argv) > 1 and sys.argv[1] == '-nogui':
	VB = BrickFactory()
	VB.start()
	#while True:
	#	time.sleep(100)
else:
	VB = VBGUI()

