.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH virtualbricks 1 "December 4, 2011" "" ""

.SH NAME
virtualbricks \- an all in one virtualisation solution

.SH SYNOPSIS
.B virtualbricks
.RI [ options ]
.br

.SH DESCRIPTION
.B virtualbricks
Virtualization suite for qemu/kvm virtual machines and vde2 networks

.PP
\fBvirtualbricks\fP is a fully featured virtualization suite and a complete GUI to manage
Qemu/KVM and Virtual Distributed Ethernet. It provides easy but detailed device 
configuration interface, programmable control of the running processes and a 
graphical interactive view of the virtual network topology.

.SH OPTIONS
.B
.IP -nogui
starts 
.B virtualbricks
in no GUI mode, only the command line interpreter.

.B
.IP -server
starts 
.B virtualbricks
in server mode. Require root privileges.

.B
.IP -noterm
starts 
.B virtualbricks
in GUI only mode, no command line.

.SH "SEE ALSO"
.BR qemu (1).

.SH "AUTHOR"
virtualbricks was written by Daniele Lacamera <daniele.lacamera@tass.be>, Francesco Apollonio <f.apollonio@ldlabs.org> and others. From an idea by Carlo Caini. The codebase is inherited from Qemulator by Rainer Haage <qemulator\-form@createweb.de>. See "copyright".

.PP
This manual page was written by Francesco Namuri <francesco@namuri.it>,
for the Debian project (but may be used by others).
